twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]
    globals:
        avatars_directory: 'uploads/photos/'
        photos_directory: 'uploads/photos/'

when@test:
    twig:
        strict_variables: true