controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
default_route:
    path: /photo
    controller: App\Controller\PhotoController::index
